typography_spectrum: 0.9828864163719118
color:
  brandStrength: 0.34524675109423697
  lightness: 0.04427149100229144
  saturation: 0.20641253632493317
  rhythmicContrast: 0.5058667419943959
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
opengraph:
  type: ''
layout_spectrum: 0.09222619934007525
author:
  name: Nate Palmer
  email: nate@designatemedia.com
  url: designatemedia.com
name: POTD
navigation:
  - name: Winter Storm on the Horseshoe
    id: d272755e-6d90-43c7-bac6-2177d1b4d8e5
    type: content
title: Photos by Nate
description: Creative Project for 2016
